import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar configuration for the Physical AI Textbook.
 * Uses autogenerated sidebar for simplicity.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      link: {
        type: 'doc',
        id: 'intro/index',
      },
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: '01-intro'},
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Foundations of Humanoid Robotics',
      link: {
        type: 'doc',
        id: 'foundations/index',
      },
      items: [
        {type: 'autogenerated', dirName: '02-foundations'},
      ],
    },
    {
      type: 'category',
      label: 'Chapter 3: Sensors and Perception',
      link: {
        type: 'doc',
        id: 'sensors/index',
      },
      items: [
        {type: 'autogenerated', dirName: '03-sensors'},
      ],
    },
    {
      type: 'category',
      label: 'Chapter 4: Actuators and Movement',
      link: {
        type: 'doc',
        id: 'actuators/index',
      },
      items: [
        {type: 'autogenerated', dirName: '04-actuators'},
      ],
    },
    {
      type: 'category',
      label: 'Chapter 5: AI Integration',
      link: {
        type: 'doc',
        id: 'ai-integration/index',
      },
      items: [
        {type: 'autogenerated', dirName: '05-ai-integration'},
      ],
    },
    {
      type: 'category',
      label: 'Chapter 6: Applications and Future',
      link: {
        type: 'doc',
        id: 'applications/index',
      },
      items: [
        {type: 'autogenerated', dirName: '06-applications'},
      ],
    },
  ],
};

export default sidebars;
